
export const backGroundPokemon = (type,searchType) =>(
        type === "fire" || searchType ==="fire"
         ? "backGround-fire"  
         : type === "water" || searchType ==="water"
         ? "backGround-water"
         : type === "grass" || searchType === "grass"
         ? "backGround-grass"
         : type === "bug" ||  searchType === "bug"
         ? "backGround-bug"
         : type === "normal"|| searchType === "normal"
         ? "backGround-normal"
         : type === "electric" || searchType === "electric"
         ? "backGround-electric"
         : type === "poison" ||  searchType === "poison"
         ? "backGround-posion"
         : type === "ground" || searchType === "ground"
         ? "backGround-ground"
         : type === "fairy" || searchType === "fairy"
         ? "backGround-fairy"
         : type === "fighting" || searchType === "fighting"
         ? "backGround-fighting"
         : type === "psychic" || searchType === "psychic"
         ? "backGround-psychic"
         : type === "rock" || searchType === "rock"
         ? "backGround-rock"
         : type === "ice" || searchType === "ice"
         ? "backGround-ice"
         : type === "dragon" || searchType === "dragon"
         ? "backGround-dragon"
         : type === "ghost" || searchType === "ghost"
         ? "backGround-ghost"
         : "")
   

